'default':
  configuration: default
  devcontainer:
    name: Duckietown Dev Container
    image: duckietown/${localWorkspaceFolderBasename}:ente-amd64
    workspaceFolder: /code/src/${localWorkspaceFolderBasename}
    mounts: 
      - source=/var/run/avahi-daemon/socket,target=/var/run/avahi-daemon/socket,type=bind
      - source=${localWorkspaceFolder},target=/code/catkin_ws/src/,type=bind
      - source=${localWorkspaceFolder/launchers,target=/launch/,type=bind}
    

    customizations:
      vscode:
        extensions: 
          - ms-iot.vscode-ros
          - ms-python.python
          - ms-vscode.cpptools
    runArgs: 
      - -it
      - --net=host
      - --rm


